### ISSUE TITLE
Is there a CLI app for the same?

### ISSUE THREAD

**Issue by deependujha** [aniketmaurya/python-project-template#14]
#### Is your feature request related to a problem? Please describe.
The template is awesome, but, I don't want my repository to say it was created from this template.

I understand this gives your repo more visibility. But I've no problem mentioning the same in my project's readme.

---

#### Describe the solution you'd like
A CLI app that creates everything for you (like `create-react-app`).

**Comment by aniketmaurya** [comment]
hi @deependujha, thank you for your interest in this project. You can clone this repo locally and update with your project details and push to github. In that case GH will not create backlink to say "it was created from this template".
